"""add cdek tables: credentials, orders, delivery_points

Revision ID: 04fe750a7dac
Revises: merge_heads_c1f9_e1eef2d9
Create Date: 2026-03-02 17:31:43.713704

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "04fe750a7dac"
down_revision = "merge_heads_c1f9_e1eef2d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cdek_delivery_points",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("city_code", sa.Integer(), nullable=True),
        sa.Column("city", sa.String(length=255), nullable=True),
        sa.Column("region", sa.String(length=255), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("work_time", sa.String(length=500), nullable=True),
        sa.Column("phones", sa.Text(), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("owner_code", sa.String(length=50), nullable=True),
        sa.Column("take_only", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("is_handout", sa.Boolean(), server_default="true", nullable=True),
        sa.Column("is_reception", sa.Boolean(), server_default="true", nullable=True),
        sa.Column("have_cashless", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("have_cash", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("allowed_cod", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("weight_min", sa.Float(), nullable=True),
        sa.Column("weight_max", sa.Float(), nullable=True),
        sa.Column("raw_data", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "cdek_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_uuid", sa.String(length=36), nullable=False),
        sa.Column("cdek_number", sa.String(length=50), nullable=True),
        sa.Column("number", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("status_date", sa.DateTime(), nullable=True),
        sa.Column("tariff_code", sa.Integer(), nullable=True),
        sa.Column("delivery_sum", sa.Float(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("recipient_name", sa.String(length=255), nullable=True),
        sa.Column("recipient_phone", sa.String(length=50), nullable=True),
        sa.Column("delivery_point", sa.String(length=50), nullable=True),
        sa.Column("is_reverse", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("raw_data", sa.Text(), nullable=True),
        sa.Column("cashbox_id", sa.Integer(), nullable=False),
        sa.Column("doc_sales_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cashbox_id"],
            ["cashboxes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doc_sales_id"],
            ["docs_sales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_uuid"),
    )
    op.create_table(
        "cdek_credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account", sa.String(length=255), nullable=False),
        sa.Column("secure_password", sa.String(length=255), nullable=False),
        sa.Column("access_token", sa.String(length=1024), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(), nullable=True),
        sa.Column("integration_cashboxes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["integration_cashboxes"],
            ["integrations_to_cashbox.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("integration_cashboxes"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cdek_credentials")
    op.drop_table("cdek_orders")
    op.drop_table("cdek_delivery_points")
    # ### end Alembic commands ###
