"""add system settings

Revision ID: 0826c2e05ec2
Revises: e67188c4adb0
Create Date: 2026-02-17 22:55:28.391619

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0826c2e05ec2"
down_revision = "e67188c4adb0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_settings_id"), "system_settings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_system_settings_key"), "system_settings", ["key"], unique=True
    )

    op.drop_column("nomenclature", "rating_details")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nomenclature",
        sa.Column(
            "rating_details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                '\'{"seo": 10, "photo": 10, "video": 50, "category": 10, "description": 10}\'::jsonb'
            ),
            autoincrement=False,
            nullable=False,
        ),
    )

    op.drop_index(op.f("ix_system_settings_key"), table_name="system_settings")
    op.drop_index(op.f("ix_system_settings_id"), table_name="system_settings")
    op.drop_table("system_settings")
