"""add cdek_cashboxsettings

Revision ID: 14f05d72d309
Revises: 04fe750a7dac
Create Date: 2026-03-04 04:24:24.458902

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "14f05d72d309"
down_revision = "04fe750a7dac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cdek_cashbox_settings",
        sa.Column("cashbox_id", sa.Integer(), nullable=False),
        sa.Column("lk_token", sa.String(length=1024), nullable=True),
        sa.Column("lk_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("template", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["cashbox_id"],
            ["cashboxes.id"],
        ),
        sa.PrimaryKeyConstraint("cashbox_id"),
    )
    op.drop_table("cdek_delivery_points")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cdek_delivery_points",
        sa.Column("code", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("city_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("city", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("region", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "country_code", sa.VARCHAR(length=2), autoincrement=False, nullable=True
        ),
        sa.Column(
            "address", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "latitude",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "longitude",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "work_time", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column("phones", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("type", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "owner_code", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "take_only",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_handout",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_reception",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "have_cashless",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "have_cash",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "allowed_cod",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "weight_min",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "weight_max",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("raw_data", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("code", name="cdek_delivery_points_pkey"),
    )
    op.drop_table("cdek_cashbox_settings")
    # ### end Alembic commands ###
