"""add cdek_order_status_history

Revision ID: 16ecd9d513ee
Revises: 14f05d72d309
Create Date: 2026-03-04 21:54:00.138439

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "16ecd9d513ee"
down_revision = "14f05d72d309"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cdek_order_status_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_uuid", sa.String(length=36), nullable=False),
        sa.Column("status_code", sa.String(length=50), nullable=False),
        sa.Column("status_name", sa.String(length=255), nullable=True),
        sa.Column("date_time", sa.DateTime(), nullable=False),
        sa.Column("reason_code", sa.String(length=50), nullable=True),
        sa.Column("reason_description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["order_uuid"],
            ["cdek_orders.order_uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cdek_order_status_history")
    # ### end Alembic commands ###
