"""add segment_tags nomenclature and hash_tag segments

Revision ID: 1ff18b33f06c
Revises: 15f770dfcf11
Create Date: 2026-03-09 18:20:13.490795

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1ff18b33f06c"
down_revision = "15f770dfcf11"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nomenclature",
        sa.Column("segment_tags", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column("segments", sa.Column("hash_tag", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nomenclature", "segment_tags")
    op.drop_column("segments", "hash_tag")
    # ### end Alembic commands ###
