"""nomenclature_add_global_category_id

Revision ID: 7dd810c97afc
Revises: 16d87642e03c
Create Date: 2025-12-25 15:43:11.911941

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7dd810c97afc"
down_revision = "16d87642e03c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nomenclature", sa.Column("global_category_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_nomenclature_global_category_id"),
        "nomenclature",
        ["global_category_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "nomenclature",
        "global_categories",
        ["global_category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "nomenclature", type_="foreignkey")
    op.drop_index(op.f("ix_nomenclature_global_category_id"), table_name="nomenclature")
    op.drop_column("nomenclature", "global_category_id")
    # ### end Alembic commands ###
