"""tg bot settings

Revision ID: 6c9004dfe327
Revises: c7966529d7af
Create Date: 2026-04-26 02:58:57.988115

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6c9004dfe327"
down_revision = "c7966529d7af"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tg_bot_settings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tg_account_id", sa.Integer(), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["tg_account_id"],
            ["tg_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tg_bot_settings_id"), "tg_bot_settings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_tg_bot_settings_tg_account_id"),
        "tg_bot_settings",
        ["tg_account_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tg_bot_settings_tg_account_id"), table_name="tg_bot_settings"
    )
    op.drop_index(op.f("ix_tg_bot_settings_id"), table_name="tg_bot_settings")
    op.drop_table("tg_bot_settings")
    # ### end Alembic commands ###
