"""add_production_time_to_nomenclature

Revision ID: 8744e1ee787b
Revises: optimize_marketplace_001
Create Date: 2026-01-11 21:24:36.130437

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8744e1ee787b"
down_revision = "optimize_marketplace_001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nomenclature",
        sa.Column("production_time_min_from", sa.Integer(), nullable=True),
    )
    op.add_column(
        "nomenclature", sa.Column("production_time_min_to", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nomenclature", "production_time_min_to")
    op.drop_column("nomenclature", "production_time_min_from")
    # ### end Alembic commands ###
