"""add segments types

Revision ID: acdd6f916a98
Revises: 6a81736a1af9
Create Date: 2026-03-22 23:51:23.073695

"""

import json
import os

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "acdd6f916a98"
down_revision = "6a81736a1af9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "segments_types",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_segments_types_id"), "segments_types", ["id"], unique=False
    )

    fixtures_path = os.path.join(
        os.path.dirname(__file__), "..", "..", "initial_data", "segments_types.json"
    )

    if os.path.exists(fixtures_path):
        with open(fixtures_path, "r", encoding="UTF-8") as file:
            segments = json.load(file)

        if segments:
            op.bulk_insert(
                sa.table(
                    "segments_types",
                    sa.column("name", sa.String()),
                ),
                segments,
            )
            print(f"Loaded {len(segments)} segments types from fixtures")
    else:
        print(f"Warning: fixtures file not found at {fixtures_path}")

    op.add_column("segments", sa.Column("type", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_segments_type"), "segments", ["type"], unique=False)
    op.execute(
        "UPDATE segments SET type = CASE WHEN is_default = true THEN 1 ELSE 2 END"
    )
    op.create_foreign_key(
        "segments_type_fkey", "segments", "segments_types", ["type"], ["id"]
    )

    op.drop_column("segments", "is_default")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("segments", sa.Column("is_default", sa.Boolean(), nullable=True))
    op.drop_constraint("segments_type_fkey", "segments", type_="foreignkey")
    op.drop_index(op.f("ix_segments_type"), table_name="segments")
    op.drop_column("segments", "type")
    op.execute(sa.text("DELETE FROM segments_types"))
    op.drop_index(op.f("ix_segments_types_id"), table_name="segments_types")
    op.drop_table("segments_types")
    # ### end Alembic commands ###
