"""add_deleted_at_to_payboxes

Revision ID: d37339fcefc8
Revises: 72ec35513686
Create Date: 2026-01-03 14:13:24.602391

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d37339fcefc8"
down_revision = "72ec35513686"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payboxes", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payboxes", "deleted_at")
    # ### end Alembic commands ###
