"""add folders and folders entities

Revision ID: d828f3b06324
Revises: d9316059669e
Create Date: 2026-03-15 03:06:01.239972

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d828f3b06324"
down_revision = "d9316059669e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folders",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("cashbox_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("previous_id", sa.BigInteger(), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["cashbox_id"],
            ["cashboxes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_id"],
            ["folders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["relation_tg_cashboxes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_folders_cashbox_id"), "folders", ["cashbox_id"], unique=False
    )
    op.create_index(op.f("ix_folders_owner_id"), "folders", ["owner_id"], unique=False)
    op.create_index(
        "ix_folders_cashbox_previous",
        "folders",
        ["cashbox_id", "previous_id"],
        unique=False,
    )
    op.create_index(op.f("ix_folders_id"), "folders", ["id"], unique=False)
    op.create_index(
        op.f("ix_folders_previous_id"), "folders", ["previous_id"], unique=False
    )
    op.create_table(
        "folders_entities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("folder_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["folders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["relation_tg_cashboxes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_type",
            "entity_id",
            "folder_id",
            name="uq_folder_entity_type_id_folder_id",
        ),
    )
    op.create_index(
        "ix_folder_entity_id_folder",
        "folders_entities",
        ["entity_id", "folder_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_folders_entities_entity_id"),
        "folders_entities",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_folders_entities_folder_id"),
        "folders_entities",
        ["folder_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_folders_entities_id"), "folders_entities", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_folders_entities_owner_id"), "folders", ["owner_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_folders_entities_id"), table_name="folders_entities")
    op.drop_index(op.f("ix_folders_entities_folder_id"), table_name="folders_entities")
    op.drop_index(op.f("ix_folders_entities_entity_id"), table_name="folders_entities")
    op.drop_index("ix_folder_entity_id_folder", table_name="folders_entities")
    op.drop_table("folders_entities")
    op.drop_index(op.f("ix_folders_previous_id"), table_name="folders")
    op.drop_index(op.f("ix_folders_id"), table_name="folders")
    op.drop_index("ix_folders_cashbox_previous", table_name="folders")
    op.drop_index(op.f("ix_folders_cashbox_id"), table_name="folders")
    op.drop_table("folders")
    # ### end Alembic commands ###
