"""add segment description

Revision ID: d9316059669e
Revises: 920f89a5a654
Create Date: 2026-03-13 00:58:39.101616

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d9316059669e"
down_revision = "89b7dd697ac0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("segments", sa.Column("description", sa.String(), nullable=True))
    op.add_column(
        "segments",
        sa.Column(
            "is_default", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("segments", "description")
    op.drop_column("segments", "is_default")
    # ### end Alembic commands ###
