"""add cdek_city

Revision ID: dd984cc03576
Revises: 16ecd9d513ee
Create Date: 2026-03-04 22:47:28.427299

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dd984cc03576"
down_revision = "16ecd9d513ee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cdek_order_status_history",
        sa.Column("city", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cdek_order_status_history", "city")
    # ### end Alembic commands ###
